### PR TITLE
Display self delegation coin estimation according to power reduction

### PR DESCRIPTION
**Pull request by nnkken**
This fixes the wrong token estimation after self token delegation in validator info page, in the case that power reduction is different from staking fraction.

screenshot_2020-01-13_at_12 05 36

The above example shows the case in LikeCoin chain, where the actual self delegation token should be ~85,138 LIKE.

### CODE REVIEW

**Comment by nnkken** [comment]
It seems the `likechain` branch is quite old and not matching the current code using on likecoin.bigdipper.live .
Should I cherry-pick my commit base on the `likechain` branch?

**Comment by kwunyeung** [comment]
Let me rebase with the latest master first

**Comment by kwunyeung** [comment]
@nnkken I have rebased the branch with the latest release. There is no conflicts but you may have to update some code. We have get rid of the `style.css` and the colour can defined in an scss file. So please move the colour to the scss file. The structure of `settings.json` is updated. We have a `coins` object in it to define the display parameters for multiple coins.

**Comment by nnkken** [comment]
You mean I should also move all the previously customized colors into `client/styles.scss`?
Also, should every coin have it's own `powerReduction` param?

**Comment by kwunyeung** [comment]
@nnkken I think only changing the primary colour will do. So just one value in the SCSS file.

Oh right... Seems the powerReduction is missing in the coins object. Can you add it too? Thanks!

**Comment by nnkken** [comment]
I found the implementation in `both/utils/coins.js` weird, the static variables are changed during the construction of coins objects. The logic is also unclear.
I would like to rewrite it by storing a reference to one of the objects in `coinList` array in each `Coin` object instance, so when converting / displaying the instance can read the data instead of relying on static variables.

Also, I assume that there will be only one staking denom in each chain? Then it would be misleading by having names like `stakingDenom` for each coins in `settings.json`.
I suggest using a structure like below:
```JSON
{
    "bondDenom": "uatom",
    "powerReduction": null,
    "coins": [
        {
            "denom": "uatom",
            "displayName": "ATOM",
            "displayNamePlural": "ATOMS",
            "fraction": 1000000
        }, 
        {
            "denom": "umuon",
            "displayName": "MUON",
            "displayNamePlural": "MUONS",
            "fraction": 1000000
        }
    ]
}
```

Notes:
 - the `bondDenom` name is to align with `genesis.json`
 - `powerReduction` by default will be the `fraction` of `bondDenom` 
 - changed `mintingDenom` to `denom`, I think it is clearer
 - the code should fallback `displayNamePlural` to displayName + 's'

**Comment by kwunyeung** [comment]
@nnkken Thanks for the suggestion. Yes I do find the code in `coins.js` strange as well. I'm asking my colleague to rewrite it. You suggestion on the coin list structure is a lot clearer. I prefer the `powerReduction` should always be a positive number and default to `1000000` instead of `null`.

**Comment by kwunyeung** [comment]
@MonikaCat can you take a look and see if you can adapt the structure suggested by @nnkken ?

**Comment by nnkken** [comment]
I've finished the refactoring, will push to this PR within today.

**Comment by nnkken** [comment]
Pushed. The refactoring is in commit `0ae8a9`.

**Comment by kwunyeung** [comment]
@MonikaCat please review the code here and see the refactoring of settings should be cherry picked to master branch. Thanks!

**Comment by kwunyeung** [comment]
@MonikaCat please rebase the `likechain` branch to the latest `master`, then help solving conflicts with @nnkken 's PR. Thanks!

**Pull request merged**
