### PR TITLE
feat: add Agoric-specific Eventual Send transaction

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

Added the Agoric-specific `/agoric.swingset.MsgDeliverInbound` "Eventual Send" transaction type support.

This is a simple transaction that predates IBC.  Here is how it displays:

Screen Shot 2021-03-15 at 9 09 14 PM

## Checklist
- [x] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Run `meteor npm run lint`
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by michaelfig** [comment]
Oh, please don't merge yet.  I forgot another message I should decode:

Screen Shot 2021-03-15 at 10 59 20 PM

**Comment by michaelfig** [comment]
R4R, thank you!

Screen Shot 2021-03-18 at 12 23 41 AM

**Comment by michaelfig** [comment]
@kwunyeung I've resolved the latest conflicts, and this PR is ready-for-review again.

**Comment by kwunyeung** [comment]
@michaelfig I will merge this PR into a separate `agoric` branch. I want to keep the `master` to be cosmos generic.

**Comment by michaelfig** [comment]
> @michaelfig I will merge this PR into a separate `agoric` branch. I want to keep the `master` to be cosmos generic.

Oh, okay.  For the future, would you like me to submit PRs to maintain that `agoric` branch, or do you expect to keep it up-to-date?  If you want me to maintain, then perhaps I will just keep a fork at agoric-labs/big-dipper.

**Comment by kwunyeung** [comment]
@michaelfig keeping your fork will be nice. 😉

**Review by kwunyeung — APPROVED** [review]
LGTM

**Pull request merged**
