### PR TITLE
Dockerize big-dipper

### PR DESCRIPTION
**Pull request by orkunkl**
## Description
Dockerized the application to make deployment easier.

## Checklist
- [x] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by kwunyeung** [comment]
@orkunkl thank you!

**Comment by orkunkl** [comment]
thank you for making this beautiful application 🙇‍♂️ @kwunyeung

**Comment by kwunyeung** [comment]
@davepuchyr I think the last 4 commits are better be in a separate branch as those code changes are quite specific to IOV. We are currently in organizing the versioning. The `master` branch will soon hold the latest code targeting to `v0.38.x` and I will merge the docker file after that. Thanks!

**Comment by davepuchyr** [comment]
> @davepuchyr I think the last 4 commits are better be in a separate branch as those code changes are quite specific to IOV. We are currently in organizing the versioning. The `master` branch will soon hold the latest code targeting to `v0.38.x` and I will merge the docker file after that. Thanks!

I wasn't aware of this PR.  Indeed, all my commits are very IOV specific and I had no intention of pushing them into your repo.  Sorry for causing confusion.

**Comment by kwunyeung** [comment]
@davepuchyr thanks but the docker file from @orkunkl is a good one. 🎉

**Comment by orkunkl** [comment]
Sorry for the confusion. It's my bad. I will create a PR with only dockerfile commit in the next days. For now closing the PR.

**Pull request closed without merging**
