### PR TITLE
Fixed chain.updateStatus of gov params path 

### PR DESCRIPTION
**Pull request by MinseokOh**
## Description

If enable the gov module in `settings.json`. The error repeats in this path.

`/cosmos/gov/v1beta1/params`

```
{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}
```
cosmos sdk explains `params_type defines which parameters to query for, can be one of "voting", "tallying" or "deposit".`

So i fixed it but if is known issue please discard this PR.

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Run `meteor npm run lint`
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by kwunyeung** [comment]
Thanks! This PR fixes #491

**Comment by MinseokOh** [comment]
thanks for reply @kwunyeung  sould i add` CHANGELOG.md`?

**Comment by kwunyeung** [comment]
@MinseokOh yes please add an entry in `CHANGLOG.md`. Thanks!

**Comment by MinseokOh** [comment]
Added in 33ecc20

**Comment by kwunyeung** [comment]
@MinseokOh `master` has been updated. Please resolve conflicts.

**Pull request closed without merging**
