### PR TITLE
fix: improve Russian translation

### PR DESCRIPTION
**Pull request by Freak12Techno**
## Description

Improves Russian translation. The one on the website right now is really of a bad quality.
This isn't perfect and likely needs fixes later, but is way better than the current one.

## Checklist
- [x] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Run `meteor npm run lint`
- [ ] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by Freak12Techno** [comment]
@kwunyeung not sure who to ask for a review, can you review it or assign someone to do so?

**Comment by kwunyeung** [comment]
@Zheng-Shilin can you help reviewing the translations?

**Comment by Zheng-Shilin** [comment]
Looks great!

**Review by Zheng-Shilin — APPROVED** [review]
Looks good

**Pull request merged**
